2022-05-25 16:05:28,321 Downloading and reading artifact
wandb: ERROR Project mateuscichelero/exercise_5 does not contain artifact: "preprocessing_data.csv:latest"
Traceback (most recent call last):
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project mateuscichelero/exercise_5 does not contain artifact: "preprocessing_data.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 122, in <module>
    go(args)
  File "run.py", line 21, in go
    artifact = run.use_artifact(args.input_artifact)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/mateus/miniconda3/envs/mlflow-2f145eba00834acf5a8352c413d14997e544f6bf/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project mateuscichelero/exercise_5 does not contain artifact: "preprocessing_data.csv:latest"
